### ISSUE TITLE
Can't Export Recordings

### ISSUE THREAD

**Issue by dukeblue** [jessedp/tablo-tools-electron#107]
**Describe the bug**

**To Reproduce**
1. Go to Browse Recordings.
2. Click on Manual (etc)
3. Choose a program.
4. Attempt export
5. See error: "Failed after 00:00:00"

**Expected behavior**
Successfully exports recording.

**Screenshots**
![image](https://user-images.githubusercontent.com/91165150/153654005-56e7b727-d537-4492-af65-958f91dc107e.png)

**Environment:**
 - OS: Win 10
 - App Version from the Home screen: v0.2.4

**Comment by dukeblue** [comment]
@jessedp is this something you've seen?

**Comment by dougK44883** [comment]
I have seen the red Failed box before, long ago.  I can't recall the specifics.  I recall despite the No Log message there was an export log (no long because it didn't finish/close successfully.

Suggestions, Rediscover your tablo(s) then Reload recordings.
Verify you can watch the recording via Tablo Tools and/or tablo via other streaming streaming device.

**Comment by dukeblue** [comment]
@dougK44883 I wasn't able to watch from Tablo Tools, fwiw.

**Comment by dukeblue** [comment]
I don't see anything in the logs directory from attempting to watch or export.

**Comment by dukeblue** [comment]
@dougK44883, thanks for the helpful debugging steps. I was fiddling with the HDD earlier and failed to get it hooked up properly. Sorry for the false alarm. Thanks!
