### ISSUE TITLE
Allow Formats for Exported File names

### ISSUE THREAD

**Issue by jessedp** [jessedp/tablo-tools-electron#45]
Try to make an easy way to enter filename formats using all of the Airing/Show/Channel data at our disposal.

**Comment by dougK44883** [comment]
How in depth are you getting with this and https://github.com/jessedp/tablo-tools-electron/issues/27#issue-637947972.  If you allow complete free-form, possibility of template per show and/or global.

I know I'm not like every[any]one else.  Currently I use a script to offload my shows, due to OCD there's different reasons I want specific naming conventions for different reasons.  Just for some examples, for insight and flexibility.

For me, current SitComs - watch and delete.  Episode titles are pointless, ShowName s00e00 just to keep things in order works.  (Don't need ridiculously long filenames either)

Archiving some shows, EpisodeTitle matters.  Iconic shows like, Seinfeld or Friends - the title says it all!.

Here's just a quirk, sometimes, ridiculously long filenames, I'll rename the show like "America's Funniest Home Videos"  "AFV - s00e00"  just feel that much better about things.

Other shows, season and episode aren't relevant and it's EpisodeTitle matters.  "Modern Marvels - Alaska" over "Modern Marvels - s00e00" but this isn't too strong.

Occasionally I'll have to recordings of the same.  Usually a segmented recording, rare incident, who knows why.  A "file exsist, append [something] to second export" so as not to loose anything and/or have to interrupt the process figure out what you want now.  Generally it's painless to delete an unnecessary file than to realize later you should have exported "the other one".

Depending how you sanitize filenames -from show titles- path spec is probably part of file name, but please clean out characters that shouldn't be there even if a "file browser" can deal with it.

These are just some perspectives, unfortunately you'll never be everything for everyone -- but you've got a lot for many!!  THANKS!

**Comment by jessedp** [comment]
The intent with #27 is that so long as a file can be written, it will - even if you decide to call it, say, "C:\tmp\shopping list.txt". All/almost all manual.

This will be at most a restricted version of that. I'm going to help you create your own custom, reusable file name formats. For example, the following "template" I now have working exactly recreates the current Episode Format in use:
```{{episodePath}}/{{showTitle}}/Season {{seasonNum}]/{{showTitle}} - {{this.episodeNum}}.{{EXT}}```
gives us:
```/home/jesse/TabloRecordings/Saturday Night Live/Season 00/Saturday Night Live - s00e00.mp4```

Everything inside ```{{}}``` is data about the recording and can not be freeform. What you said works. Someone could stick the Network as a directory. Get rid of directories completely. It'll make more sense as I put out 0.2.2 betas that let people can play with and comment on.

Then there's how to use/apply them, which gets trickier. The base goal is that you can create formats, save them, and reuse them. The easiest re-use is replacing the default formats with custom ones. I need to get further along to determine exactly how you'll go about those more specific use cases.

**Comment by dougK44883** [comment]
Beautiful!  Completely flexible and customizable.  Many users may have just took what they got... because that's all they had (or what they were familiar with from Plex)  and never knew they wanted it different.  

I know it's an example, what little I know about `ffmpeg`, it's _picky_ about filename extensions.  Like if you don't specify _.mp4_ - it pukes.  If you give it _.txt_ ?  I know it's possible to specify various formatting, but  giving the default .mp4 and giving the `{{EXT}}` as variable.

 `{{this.episodeNum}}` encompass _s00e00_ while there's still `{{seasonNum}]`, presumably same for episode?  Is there just one complete {{this.Show}}  for a default (ie) _ShowName - s00e00.mp4_  or probably with  _- EpisodeTitle_ in there.
