### ISSUE TITLE
Extra links for context menu

### ISSUE THREAD

**Issue by jessedp** [jessedp/tablo-tools-electron#55]
from [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) "``Copy Link`` for links" could someday possible give the tablo URL to the recording ie)
 
    http://tabloIP:8885/recordings/series/episodes/151217

_Originally posted by @dougK44883 in https://github.com/jessedp/tablo-tools-electron/issues/50#issuecomment-650603994_

**Comment by jessedp** [comment]
With that in particular, what's the need? If it's just to see the raw JSON that makes things up, I was planning on adding that with #54 (which I could do more of elsewhere). I'm certainly not opposed trying some sort of shortcut that makes sense.

**Comment by dougK44883** [comment]
Trouble shooting, access to objectID -> directory "number".

Had recordings not listed as failed, taking up space yet not playable.  Discovered the segs.ts were all present but the playlist.m3u8 was missing (rare power outage/storm maybe)

It's not common, but occasionally it has uses to dig through.  Get playlist to play directly via media player or, less often, to stream through ffmpeg with custom settings (not that hardly anyone knows what they are).

because it'd be less hassle than sorting through ``~/.config/tablo-tools/SID_XXXXXXX.db``

**Comment by jessedp** [comment]
I think the only thing left from this that isn't covered via the Detail popup and copy menu options is:
> stream through ffmpeg with custom settings

If there's ever much interest in it, I could add "rollup" controls for that (like saved searches and naming templates), but probably will allow passing ffmpeg opts straight through assuming I get the cli version working. Point - that will go in another issue.
